### ISSUE TITLE
diff: /../Podfile.lock: No such file or directory

### ISSUE THREAD

**Issue by Gnahceg** [coderyi/Eleven#1]
当我准备运行项目时，出现了如下的报错信息：

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

请问该如何解决？谢谢

**Comment by coderyi** [comment]
因为你没有安装pod 的库， 你可以cd podfile所在文件，然后运行pod install

**Comment by Gnahceg** [comment]
你好，pod install 之后刚才的问题解决了，不过现在还有一个报错信息：

ld: library not found for -lREFrostedViewController
clang: error: linker command failed with exit code 1 (use -v to see invocation)

请问这个该如何解决？谢谢～

**Comment by coderyi** [comment]
你确定 REFrostedViewController这个类库 已经安装进来了吗

**Comment by Gnahceg** [comment]
哈哈，果然是 CocoaPods 用的不熟练，pod update 之后问题解决了，非常感谢。

**Comment by coderyi** [comment]
那就行 谢谢支持，还希望多多对代码提出意见，欢迎提交pull

**Comment by Gnahceg** [comment]
好！
