### ISSUE TITLE
你好,项目跑不起来,遇到了下面几个问题,盼复!

### ISSUE THREAD

**Issue by MarginBS** [coderyi/Eleven#8]
先说说我做了什么:
1.clone到本地.
2.pod install podfile.
3.开始跑项目run.
出现的问题:
1.报了三个错误--
```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
我相信是与自定义的脚本有关所以我勾选了run script only when run..选项,也尝试删除了你的自定义脚本,因为我确定我已经pod install安装了依赖.然后出现了别的问题.
2.**YiRefreshHeader.h' file not found**,出现了依赖框架头文件找不到的问题...我也尝试重新设定header search paths,解决完头文件找不到的问题后出现了另外一个问题
3.运行后崩溃了:原因是REFrosterViewController的分类方法`- (void)re_displayController:(UIViewController *)controller frame:(CGRect)frame` 是unrecognized selector 这种错误,这我就不知道怎么办了,毕竟这是第三方框架的问题.
---
最后,祝好.

**Comment by MarginBS** [comment]
对了,还出现了`ld: library not found for -lPods`这个错误,如果我理解的没错应该是libpods.a这个静态库找不到吧
![image](https://cloud.githubusercontent.com/assets/13362686/17075785/4ec34f94-50d1-11e6-8d0a-db81a05617dd.png)
所以我删除了libpods.a 添加了
![image](https://cloud.githubusercontent.com/assets/13362686/17075798/ebe43680-50d1-11e6-9c2f-9ad4e25fae48.png)
然后还出现了copy resource那个脚本的错误,删除了以后,可以运行成功,但还是因为第三方框架的那个分类方法导致崩溃! 
```
ElevenPlayer:Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[REFrostedViewController re_displayController:frame:]:
```

**Comment by leewaycn** [comment]
菜鸟？
我这里正常运行。

**Comment by coderyi** [comment]
你好 请问您有cd 到项目根目录，然后运行 pod install  吗

**Comment by MarginBS** [comment]
恩 有的 我看过你关闭的issue.我描述的做了什么也说明了执行了pod install.

```
  ~/Desktop/Eleven-master  pwd
/Users/MJ/Desktop/Eleven-master
  ~/Desktop/Eleven-master  ls
Documents          Eleven.xcodeproj   ElevenTests        Podfile.lock
Eleven             Eleven.xcworkspace Podfile            README.md
 ~/Desktop/Eleven-master  pod install
Updating local specs repositories

CocoaPods 1.1.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing REFrostedViewController (2.4.8)
Installing YiRefresh (0.9.3)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total
pods installed.
```

**Comment by MarginBS** [comment]
附上截图:
![image](https://cloud.githubusercontent.com/assets/13362686/17077603/efefcc40-5107-11e6-8d1e-7b110c5aec01.png)

**Comment by coderyi** [comment]
我的pod版本是1.0.0,可能是版本不一样，你试一下把我的podfile 的   
<pre>
target “Eleven” do
end
</pre>

这两行去掉，再移除你安装的pods目录然后pod install试一下

**Comment by MarginBS** [comment]
谢了,确认是pod版本问题.
